
services:

  spark-master:
    image: docker.io/bitnami/spark:3.3
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
    ports:
      - '9090:8080'
      - '4040:4040'
      - '7077:7077'
    networks:
      - confluent
    volumes:
      - ./include/spark-code:/spark-code
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    networks:
      - confluent
    volumes:
      - ./include/spark-code:/spark-code


  cassandra_db:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - confluent

networks:
  confluent: